# Generated by Django 5.1.4 on 2025-12-24 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text="Student's assigned class", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_classes.schoolclass'),
        ),
    ]
