# Generated by Django 5.1.4 on 2025-12-23 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('midterm', 'Mid-Term'), ('final', 'Final'), ('quarterly', 'Quarterly'), ('unit_test', 'Unit Test')], max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admit_card_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='exams.exam')),
            ],
            options={
                'db_table': 'admit_cards',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('max_marks', models.IntegerField()),
                ('passing_marks', models.IntegerField()),
                ('exam_date', models.DateField()),
                ('duration_minutes', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.exam')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'exam_subjects',
                'ordering': ['exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'Fail')], max_length=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.examsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['tenant', 'academic_year'], name='exams_tenant__d6559f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='admitcard',
            unique_together={('student', 'exam')},
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['tenant', 'student'], name='results_tenant__e3a729_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'exam_subject')},
        ),
    ]
