# Generated by Django 5.1.4 on 2025-12-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
