# Generated by Django 5.1.4 on 2025-12-26 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_classes', '0001_initial'),
        ('students', '0002_student_school_class'),
        ('teachers', '0002_teacher_department_teacher_salary'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.CharField(blank=True, help_text='e.g., A, B, C', max_length=10, null=True)),
                ('credits', models.IntegerField(default=0)),
                ('duration_weeks', models.IntegerField(default=16, help_text='Course duration in weeks')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('summer', 'Summer'), ('annual', 'Annual')], default='1', max_length=20)),
                ('syllabus', models.TextField(blank=True, null=True)),
                ('course_objectives', models.TextField(blank=True, null=True)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_teachers', models.ManyToManyField(blank=True, related_name='additional_courses', to='teachers.teacher')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
                ('primary_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_courses', to='teachers.teacher')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='school_classes.schoolclass')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tenants.tenant')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('lesson', 'Lesson'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('resource', 'Resource'), ('video', 'Video'), ('reading', 'Reading Material'), ('lab', 'Lab/Practical')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, help_text='Main content or instructions', null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('max_points', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'course_contents',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.coursecontent')),
            ],
            options={
                'db_table': 'content_progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'course_enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('learning_objectives', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_hours', models.IntegerField(default=0, help_text='Estimated hours to complete')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'course_modules',
                'ordering': ['course', 'order', 'module_number'],
            },
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.coursemodule'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['tenant', 'school_class', 'section'], name='courses_tenant__bb12e8_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['tenant', 'academic_year', 'semester'], name='courses_tenant__78bc25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('tenant', 'course_code', 'academic_year', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='contentprogress',
            unique_together={('student', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'module_number')},
        ),
    ]
