# Generated by Django 5.1.4 on 2025-12-24 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_teacher_department_teacher_salary'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(help_text='e.g., 8, 9, 10', max_length=10)),
                ('section', models.CharField(help_text='e.g., A, B, C', max_length=10)),
                ('class_name', models.CharField(help_text='e.g., Grade 8-A', max_length=100)),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Class teacher will automatically become counselor for all students in this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='teachers.teacher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'School Class',
                'verbose_name_plural': 'School Classes',
                'db_table': 'school_classes',
                'ordering': ['grade', 'section'],
                'unique_together': {('tenant', 'grade', 'section', 'academic_year')},
            },
        ),
    ]
