# Generated by Django 5.1.4 on 2025-12-25 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('pickup_point', models.CharField(max_length=200)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transport_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('mini_bus', 'Mini Bus')], default='bus', max_length=20)),
                ('capacity', models.IntegerField()),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=20)),
                ('driver_license', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transport_vehicles',
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.RemoveIndex(
            model_name='bus',
            name='transport_b_tenant__6ccf97_idx',
        ),
        migrations.RemoveIndex(
            model_name='busassignment',
            name='transport_b_tenant__ff7fb9_idx',
        ),
        migrations.RemoveField(
            model_name='route',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_location',
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='drop_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='route_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='busassignment',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='transport.route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.JSONField(default=list, help_text='List of stops with timings'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='transport.route'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='transport.vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['tenant', 'status'], name='transport_v_tenant__88b7da_idx'),
        ),
        migrations.AddIndex(
            model_name='transportassignment',
            index=models.Index(fields=['tenant', 'is_active'], name='transport_a_tenant__57cc65_idx'),
        ),
        migrations.AddIndex(
            model_name='transportassignment',
            index=models.Index(fields=['content_type', 'object_id'], name='transport_a_content_297121_idx'),
        ),
    ]
