# Generated by Django 5.1.4 on 2025-12-25 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_transportassignment_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transport.route'),
        ),
    ]
